package com.ninni.dye_depot.polymer;

import com.ninni.dye_depot.DyeDepot;
import eu.pb4.polymer.resourcepack.api.PolymerResourcePackUtils;
import eu.pb4.polymer.resourcepack.api.ResourcePackBuilder;
import java.awt.image.BufferedImage;
import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.util.Arrays;
import java.util.Base64;
import java.util.HashMap;
import java.util.Map;
import java.util.zip.ZipEntry;
import java.util.zip.ZipInputStream;
import javax.imageio.ImageIO;
import net.fabricmc.fabric.api.event.Event;
import net.minecraft.resources.Identifier;
import net.minecraft.util.ARGB;
import net.minecraft.world.item.DyeColor;

/** Generates exact native-model cat and wolf collars for unmodified clients. */
final class DDPolymerCollarPack {
    private static final Identifier PACK_PHASE = DyeDepot.modLoc("collar_textures");
    private static final String[] CAT_VARIANTS = {
        "tabby", "black", "red", "siamese", "british_shorthair", "calico",
        "persian", "ragdoll", "white", "jellie", "all_black"
    };
    private static final Map<String, String> WOLF_VARIANTS = Map.ofEntries(
            Map.entry("pale", "wolf"),
            Map.entry("spotted", "wolf_spotted"),
            Map.entry("snowy", "wolf_snowy"),
            Map.entry("black", "wolf_black"),
            Map.entry("ashen", "wolf_ashen"),
            Map.entry("rusty", "wolf_rusty"),
            Map.entry("woods", "wolf_woods"),
            Map.entry("chestnut", "wolf_chestnut"),
            Map.entry("striped", "wolf_striped")
    );

    // Vanilla 26.2 bases and masks required by the dedicated server pack
    // generator. Keeping them in one compressed payload avoids depending on
    // client-only Minecraft assets being present in a production server JAR.
    private static final String SOURCE_TEXTURES_ZIP =
        "UEsDBBQAAAAIAKYJBV0359T0FwIAABICAAARAAAAY2F0L2NhdF90YWJieS5wbmcBEgLt/YlQTkcNChoKAAAADUlIRFIAAABAAAAAIAQDAAAAULNjtwAAACpQ"
                + "TFRFAAAA8+nb6dnC8do85rWU0beh3qmEu4kQvnNzlXJWh2VKdFY+XkItUzwoPw1NXQAAAAF0Uk5TAEDm2GYAAAGWSURBVHjazdExahwxFIDhR8rEJozAhUsJ"
                + "tshFAimzMJDZnCLkItmFCaymCQkuJHlhGxfzpDmAV0/geke6S7TjMAgcr1t/CF6hHyR4AHCBzto9nLTXRJBZDoWLe0L5L/jg/BQwKLy796r5BSebBjGP0Xlb"
                + "BG8R2+vHYN0onUeI0ZSBlOvqB5x8XrTbPG7T7jBf+61qt6qj6XeciTqPo7Y4B9T/+fZduRxoteSi0S74kIonHN3VtaNceN1ytpAmRpeGOAde63qlDWVeba6k"
                + "DTEZrRGestQL1pHfoca+g9l2OhmavmLS6yF2nflf4G8WrBIrl0hUFZ/vP3a9/fkJsohLxq9cSAGesBYAAv0WfEGexmcCbdecr1C7I5QuHy4fwqgJAG94xRo9"
                + "JA8lotGYEM30B85qF4cIpZQIES0CBK9EtSK/81BC7ZJSRgIYOixZZ3XeZClFm6SUCkCbx124EUqHIYZKMAHgdc1ZY2yIUEpHk2DipmXhbTpAyQY0cMYb8Z4J"
                + "OKtevhC0Gwbn2C9f93DOHV/s4ZX7C5hE4j5COF59AAAAAElFTkSuQmCCUEsDBBQAAAAIAKYJBV3+Pk40SgEAAEUBAAAWAAAAY2F0L2NhdF90YWJieV9iYWJ5"
                + "LnBuZwFFAbr+iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAMAAABEpIrGAAAAJ1BMVEUAAAB0Vj5eQi2HZUqVclZTPCjx2jzeqYS+c3PmtZTz6dvp2cLRt6EH"
                + "IRglAAAAAXRSTlMAQObYZgAAAMxJREFUeNrdjgsOwzAIQ2Pj7APc/7wbkbK2atMD7KUiSLwSt4IUCZOhDaStDkDVPGULwWA19xzC+ymgvudbU1Add1crlMrM"
                + "33rJpBwVBEDkK7EZhEyPfMgEDjI8cieQSHfPGg+lHYF9ycy6wCmcqVm4R1sBEBE3AgnzcF8KIhkRfrdBtxkE8jaDGe16g1EQrZgtaW0DNNkUqkWxF5CRVSJ3"
                + "7emd+Qtz1iPkbGLWyw0GA0HUfbkhfDtHofd1BhDsvbPuRYbJOkNxzvBXfABRugcs48PdMQAAAABJRU5ErkJgglBLAwQUAAAACACmCQVdHrAxiDsBAAA2AQAA"
                + "EQAAAGNhdC9jYXRfYmxhY2sucG5nATYByf6JUE5HDQoaCgAAAA1JSERSAAAAQAAAACAEAwAAAFCzY7cAAAAbUExURQAAAOrq6s7Ozq+vsL5zc1qdElZTXyQk"
                + "MRwYJ14wZYEAAAABdFJOUwBA5thmAAAAyUlEQVR42s3PIY4DMQyFYcOhL2ToZkgO0JMs2wMsWLgOmcCpCvyOXSVpp62aurS/LFmyPmIRmUjFv9TyTNZNyF4D"
                + "ed58YKkDTQ2Q5CNgeQfYQQzlCbDXT8AIHH++2bIIJNYewa2MUFxg2oFZsTEAGsiasuytdWo3EBfEIcgXANwBFKPOO5grkKeIK0gu0BGYtumLJF8CXtq/GAEz"
                + "lgYi1iFQXZMLAgI6CGOAiAaooQxB3Q5YFvEiEcRvoriRPuDv3+aC0+GwyYd3Bjnpp7mySA8MAAAAAElFTkSuQmCCUEsDBBQAAAAIAKYJBV3vVlHuNAEAAC8B"
                + "AAAWAAAAY2F0L2NhdF9ibGFja19iYWJ5LnBuZwEvAdD+iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAMAAABEpIrGAAAAKlBMVEUAAAAcGCcWEx9WU1/9+fta"
                + "nRKvr7C+c3POzs7q7fDT09Pq6urBwcEkJDF1KU1+AAAAAXRSTlMAQObYZgAAALNJREFUeNrd0OEOgyAMBGDaOqe19/6vO082CDBn/LtPUzUe8SSRULh7pAOk"
                + "zjuB8DgC7qLK012aANVHKasHsKehJoQe+0FKNs+zoQSUa+h4z5FaqgKYGSBaAyPZWYQlOgt4hF8EfP0ZWP0yEBeB3OHuX8hXTSDvIjjKhqZKsawL9slx3FLq"
                + "TJEyiTIbwCew5Tk2LYVVtKtJ74/GtgXx0gfOO0wQJUFMXYcRdgoFpc7Y4a+8AIyQB10C5CK9AAAAAElFTkSuQmCCUEsDBBQAAAAIAKYJBV0+eaeBOAIAADMC"
                + "AAAPAAAAY2F0L2NhdF9yZWQucG5nATMCzP2JUE5HDQoaCgAAAA1JSERSAAAAQAAAACAIAwAAAJVDjrYAAABOUExURQAAAOedNeOMLOmVN9t5IO6kPuSGME2J"
                + "Dd+yZL6PQ+SPMeWPMOWVM75zc9WxdOCNKs7OzuukOuzmhOugOeSYMO2sPerUrurq6vS0RuqpORVK66sAAAABdFJOUwBA5thmAAABk0lEQVR42u2TW47bMBAE"
                + "OUPK69081w9O1/0vGlqDSIAh2YHzuwWIID+m0C1RZQYhiAjKCj24XM6/lrOg7NAO1Zv3gLKiHpzFZRGAyg6aJjPoUFaIrgt/Beai7WZwr7U2uBdwRuRp8omG"
                + "djIAQneCHtEB1gS+VUJ1dreGVavGOhJDwJLg0w1nowI+VcUbbwHmoAFm1uNGN8MQ4tPZSpDRBFnimwmgVsd6znt1rwNdr7ApMCMRuZdMYEYGkNn3jw9AIHgg"
                + "YBYIQAKLgYGUtbqiQ9/8BOuaHKqvAvfq9dB69B7R458EJkGPAdloEINNQQRJxKLQIAWBbgDlOQjlzmutKehQbydv5Tlar60EkQKUPJjTeH4XCRBaKqQADSab"
                + "prIHkJPKtWQFbxYDkNdBOzxqTs4CLAnIq2jPK4AkgCCgkwJWAWaTmZU9MgCKHnF75gpuNgu6Xd2rt3Z4UAFAME8PUsr6L4DsUQIkuLso2CAFA56+A/qgvErG"
                + "j15e53Q6IcrrCP2PAN5/vKPyMhyPP49Hyhev8wcZhzj5B5C59wAAAABJRU5ErkJgglBLAwQUAAAACACmCQVdk8fBqVQBAABPAQAAFAAAAGNhdC9jYXRfcmVk"
                + "X2JhYnkucG5nAU8BsP6JUE5HDQoaCgAAAA1JSERSAAAAIAAAACAIAwAAAESkisYAAAAwUExURQAAAOqpOfS0RumVN/35+02JDd+yZL6PQ9WxdL5zc8HBwdO3"
                + "hert8OrUruedNeOMLOtD+6UAAAABdFJOUwBA5thmAAAAzUlEQVR42t3QgW6DMAwE0JzH6Dbsu///28WRC2rU8AF9oBChU3JyS/rqFBFqg6HWJyNoOo5jFVAe"
                + "IB0aAYnnWwFLSi0BINmKIJgkgyAmPH4f6K6A2Xd/TNCw7z/7jitAoFACoPZKIjNDUhV4iwSjaysak/J1AGYId28rOSq/C1jnHn7bwe9Koou3AchkQqotQb4O"
                + "wEAMY0tKbBcxPKhwj9qmNtm2s0qtk/MPrNYJWTlQEIH5jLr0zz1SfubAusMGKhHbtuhQ1h3K3OGj/AN8MwwNdgmnbwAAAABJRU5ErkJgglBLAwQUAAAACACm"
                + "CQVdxJTHR70BAAC4AQAAEwAAAGNhdC9jYXRfc2lhbWVzZS5wbmcBuAFH/olQTkcNChoKAAAADUlIRFIAAABAAAAAIAQDAAAAULNjtwAAACdQTFRFAAAA8/Lq"
                + "7+vb6urq6dzH39DB0L2xvbasnJGLDX/IZVNJVUQ7MScg/jTV5AAAAAF0Uk5TAEDm2GYAAAE/SURBVHjazcy/asJQFMfxOwp1EvsABn0Q5ZfoaCEn7djBXIeu"
                + "rVdohw4qgXTr2gcocSyWkJPBrQXvQ9Vr/BeNlm79cuEeOB+OEKIUDCbyWZiIkqn5AbFXiWOfbtcgfC8AKe+B2WqfExd6QdRdg5vfAI0PQcCsF/p7BGSADkEn"
                + "+Hh7jScAPNlv1QfSBXIAQZiy2cMmWbMkAWgDzha46KQjgIhge03LNweGSg23gFyE96AMXFUNaCdRxGKbNs8EeM1LH4DDUTQtBtYGJLsLSmv99ZQBqhng9MRR"
                + "wBpUCbibnAZNi4Awzu3K8/IcAHaA80Av2wCvVvHhJKdAzzbA7RSAvlJKiJEtrYpcgukReGRmIT5JWnVJRYBXIPb6rcbADxM+AtkUS+U2lCwG+f4GxDXReRA8"
                + "nAf0Mu6eB+msK/55P5lrqYjo3axtAAAAAElFTkSuQmCCUEsDBBQAAAAIAKYJBV3gYHJYQQEAADwBAAAYAAAAY2F0L2NhdF9zaWFtZXNlX2JhYnkucG5nATwB"
                + "w/6JUE5HDQoaCgAAAA1JSERSAAAAIAAAACAIAwAAAESkisYAAAAnUExURQAAAFVEO2VTSZyRi+ncx9C9sd/Qwe/r2/Py6kM2LgCU8L22rDEnIHmouyMAAAAB"
                + "dFJOUwBA5thmAAAAw0lEQVR42t3RW6rDMAxFUR0dPdJG8x/vjRKoyTVx/7vAwh8bI7A0AqBHhMupaswTUcAqQFUhmhz2vS7HZQ4auR/G80AHfegtWIxRkATe"
                + "9QZIDzOLQCFGYGdRAN0ucmcHomht7DGBApYZ8gSqyNxyFTC3ReBKPwKTJ2bmmVusgj2+vGC5ZcpEaTfUJgPDzMJO0YdUpQwezU/jKv+g5GK85nPgn3nzugIl"
                + "AQVIVbmp+vyYag9MwfMONbzmHYblDm3e4af8AbcXB3t16QbwAAAAAElFTkSuQmCCUEsDBBQAAAAIAKYJBV0sMHO+lgEAAJEBAAAdAAAAY2F0L2NhdF9icml0"
                + "aXNoX3Nob3J0aGFpci5wbmcBkQFu/olQTkcNChoKAAAADUlIRFIAAABAAAAAIAQDAAAAULNjtwAAABhQTFRFAAAA79SWvLy8pqemmZ2bhoqKe36AEhkoVHXx"
                + "EQAAAAF0Uk5TAEDm2GYAAAEnSURBVHjazdE9bsMwDIZhoX/3KNUDBKKaA5SfMgcoqTmLuLf3HyrZQGInqbv2hQ0NegwRVgjhSeB+CiPJkscKD4seKZodV4BX"
                + "4IHIygwALWO/twaKGWgxm0G+D8xa7UtmuQBhpsg8f9qqe18gWID0+v1FA6C/booU0VsA2qcJ8Hvxpp9MHZQLABM+Yj64czavJomoDHBb5FLdGIlKL5yz8YwS"
                + "w5tyYrLeHZAFzcGcyHuXGWpzPZyPQEpE4SZgHJHNG5go/gKEi1fNQm9h2cvp+TgPxQJ3ZU5xBdwxFQJlVDfhqxnqGUSMI5CuQQW0FwJPQ0qMa2AGzDNILs0h"
                + "WeINmH8Ml1Jd9XpINSBMTbdtppzXQDvYCtgGY/g/gW7v73m3DSC78M/7AeNCZd6JO4BFAAAAAElFTkSuQmCCUEsDBBQAAAAIAKYJBV2OIgfFFAEAABIBAAAi"
                + "AAAAY2F0L2NhdF9icml0aXNoX3Nob3J0aGFpcl9iYWJ5LnBuZ+sM8HPn5ZLiYmBg4PX0cAkC0gogzMIMJBtD0o8DKdEAnxBXIL1nz55ly5fNnDu7rauruq5B"
                + "SFLjZeJ9E6AEY0mQXzCDw7MbaUDOak8Xx5CKW3vPBXIdVuBpeLgmld3D+teeZbYOhr/sDPb1n7vzX0tYW+NQ3HdlQTsDDgbtd0ovp9UEdfDfZ45m4Ft1z9RA"
                + "QH6CUtTEDPGFkzWY9bj9OCuMWZcZM085Y2U8Kbj1VsaafQtatzYzfq/YUnA4sorDtsQ6I//AhWNnMqt2OvT4PjDn/NiksWiV0sJ/pRXLHl76yfmY8cA34Znc"
                + "d+4zzFp9wU5xedYKh7VvVkyVrX/NvfO1apqX1uJ+oLMZPF39XNY5JTQBAFBLAwQUAAAACACmCQVdqlJLZRICAAANAgAAEgAAAGNhdC9jYXRfY2FsaWNvLnBu"
                + "ZwENAvL9iVBORw0KGgoAAAANSUhEUgAAAEAAAAAgBAMAAABQs2O3AAAAMFBMVEUAAAD////n6erc3t7v1JbJzc/lvoRx4fi6urrqoKDbnD7KiT+Ye1RPSUBC"
                + "OzISGSheOmf1AAAAAXRSTlMAQObYZgAAAYtJREFUeNrNzj1rFFEUxvEHxU4Cu7WFzoKQCIL3cBc/RvBy4KKNKEyx8UPYDJzPkSLFmXU7t5hrJ4SwsqmsJDNY"
                + "S+aCla0zu+zLsMmmzb+5xf3xcAA8NCTyGW2qk3LxCrZ60OszH6NtqOO4Cx73UrZLQOnbSwA6TQtsOjhXR0vgLCuAcJrk2+DPGjBnvgUfzAirTKx+pXpmmQFk"
                + "XgSAGjragMuff/8tgH5lFnbDXFOi4Qa8jIdHIWlAPrWSuTcnhRJZWgNKevSqP3gtooHFsykKtS3YLVfrhZNQjGwT1jGgaNMpSeaST9WMm24A+aTKhE4m9bk0"
                + "YRX5LBQ5mkIZL4SKbz9G2IkIwGweLzIKmsdbwPV4Jt6FMC+x3cHvR8fLo6KeibgXoa46IEZaBNQpeWGTxO5CVa5ARVa8o2fz7kJZE7km4HrAkpHpP6l3Fpi9"
                + "ADqwmZAZGO2A8RWRNAGn1npx775c9TtgVBBhkWUW5lCW3zsgVSLsi4Z3ACQf7wRu///h8/f7AZmnuOf9B+ghrApg1ZsxAAAAAElFTkSuQmCCUEsDBBQAAAAI"
                + "AKYJBV1WqIBpXAEAAFcBAAAXAAAAY2F0L2NhdF9jYWxpY29fYmFieS5wbmcBVwGo/olQTkcNChoKAAAADUlIRFIAAAAgAAAAIAgDAAAARKSKxgAAAC1QTFRF"
                + "AAAA8/X26u3wyok/5b6E25w+mHtUT0lA7bIyVtr16qCg/fn7Qjsy09PTwcHBPjm47QAAAAF0Uk5TAEDm2GYAAADYSURBVHja3dBLbsMwFENRke/XVqL2v9xC"
                + "gtMmRuzOewYaXeARagvQgSlptq1jvWHtoRP0u6Cye8ypuQOJEjMt0x5BecRcjotOsh2IrKqMhRvwBQfwEyDro39GhFOZKRLkbyBiMTOnZGZqryTunqQkAGpv"
                + "0c00p9qVYc7boCpMU7wLYuguyMiheR1ERPFug5mV3gaItQ9bVUa3UcbXD8g6Alk4LYc/ByLHoDYuWtpJ74+D83hP3P8IzNoCgIIIAO1FjbbMJ+fg+kR3G4t5"
                + "76fg5G7Ddt7wr3wDCF8JnuuseCcAAAAASUVORK5CYIJQSwMEFAAAAAgApgkFXQiLXUl/AQAAegEAABMAAABjYXQvY2F0X3BlcnNpYW4ucG5nAXoBhf6JUE5H"
                + "DQoaCgAAAA1JSERSAAAAQAAAACAEAwAAAFCzY7cAAAAbUExURQAAAP/qy//gsvPKjdCkbuyLemCz+KF7ZCIxUAtPo0kAAAABdFJOUwBA5thmAAABDUlEQVR4"
                + "2u2RW2oDMQxFTZMNjD/6P1cbCJIWENCFWVAHZgXtuusHiSfJlG4gB+ML1kEIOaV0NievqQLMuebEtONkRr8LOBAgYTdBpdYLafAB3ASV8C7kvTBls0uqmJEl"
                + "8jQPIVB9YauEcymBGXvh8/unCRAnQzGhMgSFAEayXTSIATKENVTVuG1b62CGWhY87qElnGSYAlIYddRTETVnqHUOBMBJhUBZGDN40L96ByGjbfsFtPVYeCjm"
                + "af5DmGAeJv0fBufr6dKHympO6rNAolE6iDkD85PgdyF7cLWXDu6AFlKCcCED+VEwA/oMJZY1FMgvQl8MfNm2NQCkPWq3B+FWoD4L4+EYFNKbf/kFEBJFgSWk"
                + "CFcAAAAASUVORK5CYIJQSwMEFAAAAAgApgkFXXjlqmwVAQAAEwEAABgAAABjYXQvY2F0X3BlcnNpYW5fYmFieS5wbmfrDPBz5+WS4mJgYOD19HAJAtIKIMzC"
                + "DCQbQ9KPAymJAJ8QVyD9/9Xp/w82fT7Ve2FJ3pvuqoXVKa6Va43Wu5UB5RhLgvyCGRye3UgDclZ6ujiGVNzaez6Q67ACT8PDNXdZJ4l9s1rM/qKHXcP4Ddfu"
                + "Azf+9hvsjkpv3ftNXaMmwYEhoWjVy2Wp09isj8kq9AkxmBwxsdeodFIRmsj07JML3yppl2PSkanbG7u2mqWc+Gq3J33FQZMLC6t9TecUXBCT0zWxvhGaMGGG"
                + "5dy4MIFk4YpJAuEdSqu0gv4u273s8NKf3H9ZDnyTm2k8J53hb1jC95bmVc95lm5SDi+TucY+q15uxpqn4reBjmbwdPVzWeeU0AQAUEsDBBQAAAAIAKYJBV3K"
                + "NGSkogEAAJ0BAAATAAAAY2F0L2NhdF9yYWdkb2xsLnBuZwGdAWL+iVBORw0KGgoAAAANSUhEUgAAAEAAAAAgBAMAAABQs2O3AAAAG1BMVEUAAAD////39/fv"
                + "7+/L5//a1tKrnpSJdGk2SnOLKjUUAAAAAXRSTlMAQObYZgAAATBJREFUeNrN0L1qAzEMwHFDaTKHDNl9L5BaKA9SIWUNFMlrhtaaC33wKnckubu017V/DFp+"
                + "/sAppRWJ+zldIiRMEXsa9QxodpoAmIAnIZMBMKvEgGh8QvtQHoCK2QBwBNZar8Cs1RgIdAeElY4Kw9ZW3WMw8QjI++dXowAAWBtBxNENqOkOTc0MQdzfCEoA"
                + "uYMmtNmKuDuw1aaQS5EBzCtZvHHJOUuUblm/otxZ/4acLfoJoFQzLrnzKF3j2lyPPQCprkQ5p4eYLwAP5szlV9AhV1fIM7A+r04WDVc0eoUyBe7cF6A7eFOA"
                + "PAX1BjoQN8U8B5VZowswd+NuBsyYhzcU5NqYoJQHMHwMgHjTADABGiD1AVf3hgAzoAGW4igtBvgn0LTUy26zXwSw2e7TP+8bHLd3bbdVOXwAAAAASUVORK5C"
                + "YIJQSwMEFAAAAAgApgkFXVNGUzciAQAAHwEAABgAAABjYXQvY2F0X3JhZ2RvbGxfYmFieS5wbmfrDPBz5+WS4mJgYOD19HAJAtIKIMzCDCQbQ9KPAymJAJ8Q"
                + "VyD9////79+/v3///ta1S6vnTeksyTTzKtb6aPQfKMdYEuQXzODw7EYakLPV08UxpOLW3nMb+ZoMRFofCjuWq4cz/2IoOt2X2a19eO9c3w21/90nTFrmJH/A"
                + "nvfw9IIohllrOBg61ZfteC7bc06KW+I5c7/gnq+CWkbM007UTbm+l+Osi+CU6li3uAMae5umPs9RvTc5qW6O6G6BD6uvmfnccAp3uPql2sKkPL5Je+GNBW/d"
                + "rm+dFXJ9262Es0+ECmq2rbm/p5L1wvHJq9qZ+oQdvKQXsSw3V8iWLNt/J4bjjsqJp70h935ExzfwG954LG6mA/QAg6ern8s6p4QmAFBLAwQUAAAACACmCQVd"
                + "2MIXfZoBAACVAQAAEQAAAGNhdC9jYXRfd2hpdGUucG5nAZUBav6JUE5HDQoaCgAAAA1JSERSAAAAQAAAACAEAwAAAFCzY7cAAAAeUExURQAAAP35+/P19urt"
                + "8OjoptPT06bl6MHBwb96pRIZKEFHBYkAAAABdFJOUwBA5thmAAABJUlEQVR42s3QUWrDMAyAYZexA8gZrK+K2HssIXaPGeFrDIrxOfay805OMWvakL3uJyAC"
                + "HxYohPAEU7XP0MOIsU+GcNMJcYA0palP2AKAAYQ+1Ad4W9DKFWQ12wftCsxqWUGUMOLoPMb31vynlnUw0C/I+PL1DWRmUbKZintBuQGazvAmDoBUW+YOWDSM"
                + "LM8QyTyYpFTpIItaeAyilkueEcDUbsBr/66gv4DgwPYBUamcHDQvjJpm0bwCmLQmdLCzvq0rJr0kOAJk+RE8L6el3zKECFSMH4AZeJEczFJM4h5I1E8LSUvN"
                + "0z1QBTDJ5oDFASFugci4HJI64BnjHRiHYcrFlAnnDWAeO0nMLAvPW4Do4CjwwmGS/gAzHgM+x+UQCNIS/nk/sntLGMbkKPQAAAAASUVORK5CYIJQSwMEFAAA"
                + "AAgApgkFXaimMqQeAQAAGwEAABYAAABjYXQvY2F0X3doaXRlX2JhYnkucG5n6wzwc+flkuJiYGDg9fRwCQLSCiDMwgwkG0PSjwMp6QCfEFcg/ffn789fv716"
                + "++Hy5csHDx4Mu/X17Saj/VVLD62bswEozVgS5BfM4PDsRhqQs87TxTGk4tbeM4FchxV4Gh6uuc0o5r39uuTbakO5BWe+sH11sv7ZpHuJq/quf8eHRkYGo8U6"
                + "v2YZRb1vM1bgy2abMKOk7ASX7EeWKIOOYwbGtR1cN54za3Zt4GYVyvQ7cXhegUIfa9Z1gc887ht4S15cf8kh/mZp69LWZ2w/mSNMXJZYf2DLmetkIHOZrTPS"
                + "ZcZij72V101f/Wl5x+rwbm5H2Y6zDDtDHn5h3dtxlDfruXTU3o/b9zH7KZq6asdYA13O4Onq57LOKaEJAFBLAwQUAAAACACmCQVdqDjhaikCAAAkAgAAEgAA"
                + "AGNhdC9jYXRfamVsbGllLnBuZwEkAtv9iVBORw0KGgoAAAANSUhEUgAAAEAAAAAgBAMAAABQs2O3AAAAKlBMVEUAAAD9+fvw8PDm5ubX19fBwcGuwJm/eqV0"
                + "dHRiYmFSUlFLSkpDQEASGSh1mGmxAAAAAXRSTlMAQObYZgAAAahJREFUeNrNkD1v1DAYxz33WJwbelKnS4TUsYmNxO7H0gkWRJ0Jvsy9CAHJyMC5bDDQ+Ia+"
                + "SqntBeh08cLC58HucUdCReb+ZOlR4p//+tsIoT2jBbxAgXEkVZgGoxZ7TbMV0qFxYeKOMFivtwJJyo9+TPHItIWVzvlGYHSyuAvAbeFRbfN8IwAIfidEfwVr"
                + "qgtT2bWy/kPwPPcjw0mxE9zqzc9fZWWcviAMgJIDY8iYvN0Jkzrdx4c1FAscU5qz2BcgGaE7AfyvKAHPaEi4IE/mOGWEArqPfkn5MTus0wIotIRVWIHbOCTE"
                + "z2wF0BY+hRW4+Zpwkb1eL2XuQVuM0pXSyNOcD6lIC9M4dA9jwoWvI3r8WC+V/Y9g6wTYU+tuJGozOBucGRMMLeccMmVdN+G2/FGODmaJv4u55EDe6+VpR/gg"
                + "z0/ShBCEKiW4YK/cPyWvyu8lEAa+g5tzMdFSdztcvvuiNi93Kq98gtO2m/BZLUxd1AVC6ppyVvj9piPM3PzPCVkDwPNKmm7JqZ6doD6+ualDvZAU9wvxuF/I"
                + "9qOjXoGMkyP0wPkN6VWniX4yGBgAAAAASUVORK5CYIJQSwMEFAAAAAgApgkFXYZg7jJuAQAAaQEAABcAAABjYXQvY2F0X2plbGxpZV9iYWJ5LnBuZwFpAZb+"
                + "iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAMAAABEpIrGAAAAMFBMVEUAAADBwcHT09NLSkpDQEBSUlFiYmF0dHTX19fm5ub9+fvw8PC/eqV9uDXq7fDz9fYB"
                + "6P3bAAAAAXRSTlMAQObYZgAAAOdJREFUeNrd0jlyAzEMRFEA3SC4SOT9b2tyZJvaRs79gk74qwbByOIEoWamcnDuPYBOvwsS9x7ghKuaHgHggE9z5YYIUBdZ"
                + "xhi9d/nGVaMdS87BGJex/ATOiGu9RhyvJHofve8gEKXWS60tEDnPkUc5l9bqfG8l38hbJGGqJmfgyT8GKXkytS5nHGC3D0GKSN30PCi1lv7phjrZ2wBOJq9j"
                + "qp5IB0DKFkSEtjE1jQAjR2TZcmgpOduUc5lN1kmeJJOboXvv4a8g2e+fYsP6mOQBVRa98xTw/BNI4JKQ8BpsJzdsrzf8K1/OZAjdqtPcwQAAAABJRU5ErkJg"
                + "glBLAwQUAAAACACmCQVd39J4WJcBAACSAQAAFQAAAGNhdC9jYXRfYWxsX2JsYWNrLnBuZwGSAW3+iVBORw0KGgoAAAANSUhEUgAAAEAAAAAgBAMAAABQs2O3"
                + "AAAAG1BMVEUAAADhuUXAeDKSaYMWFSQSEB0MCxUHBw0EBAfgt+sRAAAAAXRSTlMAQObYZgAAASVJREFUeNrN0EFqxDAMQFEvhvYchV6kjBx6AEXdZmFJvUAt"
                + "L7sa+9iVM5hOZkK67ScgAg8LFEJ4gqnad+hhxNgnS7jphDhAmtLUJ2wBwABCX+oDvC1o5Qqymu2DdgVmtawgShhxdB7jZ2v+U8s6GOgXZHx7fQEysyjZTMW9"
                + "oNwATWf4EAdAqi1zBywaRpZniGQeTFKqdJBFLTwGUcslzwhgajfgvX9X0F9AcGD7gKhUTg6aF0ZNs2heAUxaEzrYWd/WFZNeEhwBsvwInpfT0m8ZQgQqxg/A"
                + "DLxIDmYpJnEPJOqnhaSl5ukeqAKYZHPA4oAQt0BkXA5JHfCM8Q6MwzDlYsqE8wYwj50kZpaF5y1AdHAUeOEwSX+AGY8Bn+NyCARpCf+8H3vTi3EV3mH5AAAA"
                + "AElFTkSuQmCCUEsDBBQAAAAIAKYJBV3Ir35iGwEAABoBAAAaAAAAY2F0L2NhdF9hbGxfYmxhY2tfYmFieS5wbmfrDPBz5+WS4mJgYOD19HAJAtIKIMzCDCQb"
                + "Q9KPAymJAJ8QVyD9cKfrpMxmMVEVIQFZHm5RdnZeFhZ21aPC84FyjCVBfsEMDs9upAE5GzxdHEMqbu09c5Cr2YCn4eGBO/NS+A08j75ekLm3KqPq24Zj5hvW"
                + "7w9YmpF4/W+LiF0GQ8MZldX7lvWY7fjI1fF4GqOK2lzmTU7uNs1iPIsMz/j4L2La9n7iIo7dAQoTn7XYyHCyP4pYUMZvqF/AdtuhvW72+YLDjlER0Rl5E+wb"
                + "XZ1ddjG/P3BNk+Ww4dsJM1xbLLuuzNaPnXzO/8U9hid2nS8ajjNN8BbVi7/QHXFnYdnehVel619zWzFYbDCdFSIFdDuDp6ufyzqnhCYAUEsDBBQAAAAIAKYJ"
                + "BV0XUduPjwIAAIoCAAASAAAAd29sZi93b2xmX3RhbWUucG5nAYoCdf2JUE5HDQoaCgAAAA1JSERSAAAAQAAAACAIAwAAAJVDjrYAAABRUExURQAAALCqp5+a"
                + "lpqVkdXQ0JWGeZqMiIxvUqePfv///xIUFjk8P+TY2dS1pM6vlsSrnJR7aKF4Wy0tKElCOcnBwoF2bTk4Nd3a29PPz8rHyMG+vkR/BzwAAAABdFJOUwBA5thm"
                + "AAAB50lEQVR42t3Sy2okNxhA4XPk2eaCQ8Zd/f7P1tV2gi+zL52AsU0bdzEwy3wLCW0O+pEEOGTamOgJPhxXD+fDenCOObKVrwYANmxUcWkuzViaQMzYDUSz"
                + "wuLSRnfMqJL9gIMcvuJCLFAEUFzz7TiVCTgdMBfzxBshP/arRhUv+hJts+bkgyCoKOj1gPXk87PPJKJdBob6vl8fwRzNyDHRkcWRCm3DGbQpchjbTbl+CmCP"
                + "FfD4pyAoM1A3BGlUIUHzyw142rwFHufzLSCCxgAUEEwhEotLAvxh2Asfjln3C5sCuN5pbpqN7f7LP4j4JFc1KKrU1eSsrjf8PMDqKmekgjOurtwPz5xdv47w"
                + "2xyO+YNf4e8Fc4Ai/eA78MCb44bdnNg3wPdVle/KuOPNhJiwb4xtVjW3wSsleZM3D8avOx7GOAr7vsEt8QTwF6N/+WRd+InBpYTP1liBfS7OMUesLuGU9cgM"
                + "bgjZwMFmD3ecuWYUjZKF6p5gglAFwgRvoL0REiJWJASIV34cWpfYCyhJQLpMCYiiGQGZ4E5AMx0AnFMIQWEIEgC284wPUycjFozGBDGQEgSS9RBXjakNi5VY"
                + "CBSRUERUE3dusMQ/+LcnQERAFBMEAZbzbuAEwAqdeGMo0HsOyvi/+g+RAzjfQGNRbgAAAABJRU5ErkJgglBLAwQUAAAACACmCQVdzoHfq54BAACZAQAAFwAA"
                + "AHdvbGYvd29sZl90YW1lX2JhYnkucG5nAZkBZv6JUE5HDQoaCgAAAA1JSERSAAAAIAAAACAEAwAAAIFUZ8cAAAAtUExURQAAAOTY2d3a29PPz8G+vs6vlrCq"
                + "p7ygi5+alqePfpqMiKF4W4xvUjk4NRIUFrAtdC4AAAABdFJOUwBA5thmAAABGklEQVR42rWQMUoEQRBFG0SMDDYQ86plM2GpX4oKgkwVo6GpqTsME5oar8wF"
                + "RAwUE0/hEYSN3BMYegurmL6Cjxn685pPwy8Fr4XX0ttJwWcJ8uBHgnheBR7QIB21mUIM4zDyNVa0GCNmg4VppIYUwhJif7ss3qmwZwq+j6wAMNZMwfZCU/TW"
                + "ZgocDjOFsZtLCJDCPbSwOEKYOjrvIazqmhW0fefxw828JDtCAJZ7Lw/3ZRLgFLvPtzdVRJ30avZziGUVYKHj2ewAVRCr8WWk9fSK3i2MPb5yailsYbQidVGI"
                + "hzGa/7436gCUTLNyttk8IcWcBaV09vZx/uUpWJqo5LR1b4H5tHrKoHGNilfKxLR63TuoqyP3/k/+ALORVuV6pwxxAAAAAElFTkSuQmCCUEsDBBQAAAAIAKYJ"
                + "BV1iBPMiPQMAADgDAAAaAAAAd29sZi93b2xmX3Nwb3R0ZWRfdGFtZS5wbmcBOAPH/IlQTkcNChoKAAAADUlIRFIAAABAAAAAIAgDAAAAlUOOtgAAAGxQTFRF"
                + "AAAAMC83OThDQUBNKigvd1IwMzI86+Lf29PTzsbEgXuDtaipAAAAJyUq////iIGJmZGZZ2Rz2M/Kk4qQEhIVeG9zp5uaERATopulDQ0O9+3t47uaIyEmy5ls"
                + "1q+Q4o87yoQ/vnY2sGcrkF4uQvcCFAAAAAF0Uk5TAEDm2GYAAAJ6SURBVHja3dPpjtQ6EIZh11flLZkFOAvQ3Ylruf97PEmfgZlGnQHxk1f54SjyE9uS054O"
                + "sBoIKJTeJPIoj8jZIRASS0epcjGlwowboIlARNzgyAY9BgZjjAIGl/SmWoUh8POwoa7nQ8CMWY0Kyg8rmIVBnNsO2LgPuJp7gOM6MDU3//4NwkzMrjY2w+8C"
                + "u52fgKesOrZn6CuQIWDCxxyRc2Q+OMDA04PQwxNCdef0O0AQgdDETATgPmAKIhIhIqi5qaul6K3yPE0TMwBm8NzOau4s7nYLlADRZYsIUdyvZ4CpMlqbG4AN"
                + "YQLXGh6ZKQduAdq6yNaFtvxaIgKkNwYRTfNEAvCEYAKB7+wEABGl14Qk+9RlF6ZWJwIJ7fuoBNwD+AeAskB5+sgMQm1t3kDKmzAJ5zsAM98C5hmWaQLzPmub"
                + "l8Ntvxr74A7w9xX4vQBmfmBmgK4K8RvLx1B+ny74VrkCl9PpouP1mo3B8S5w+fzwf58vV+Brnb8OTS+Fqoel34/M3X8GRPT+Mpg/pdskIjx+Hfg0p9tyjoj3"
                + "AX8phZu5miXqHzIzUSlEzIznOoMFOADM3PapibKi5KKJCAymgvoXxT58fi7PAj4AdDFbVC0JFUAIKRMHmCa0Tgb+UonrTHwMLLYsuqZ/qJapoyQDD45cP9Qa"
                + "mvlUS5z+JdYDYFltWTckzb22uU09xfhSh3urtbsOnE+mJ6Y4Ata2LGtf1tR7q3PtNZW1trP62mpzPZtWG+ujFD4AWuvr/uwrqL22msj2X/tibXU7dV1cTR4D"
                + "B0Bvrdba+g607aWlbJkQ7ra6b5aZ50LZIv1q7kGF3M18V8wzSgm39Kf2H9WrNuaRd0qzAAAAAElFTkSuQmCCUEsDBBQAAAAIAKYJBV3lzHK67QEAAOgBAAAf"
                + "AAAAd29sZi93b2xmX3Nwb3R0ZWRfdGFtZV9iYWJ5LnBuZwHoARf+iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAMAAABEpIrGAAAAPFBMVEUAAAAwLzc5OENB"
                + "QE2Be4MqKC/ijzt3UjAhICQcFxkSFBawZyuQXi61qKnWr5Dr4t/OxsTb09O+djbKhD8B8ozeAAAAAXRSTlMAQObYZgAAAVpJREFUeNrVkgFyhTAIRLNAov1V"
                + "E9j737UmUaf1Bn0jUXDRgdmUEuktpcJVRLet7dvWa83T5E6KrO0om3tr29U0iQvV7F6+zX3/jovZfxzsUQhzburWtoOzmjru9byqF11RFaJq8FHxmgb55LwB"
                + "GQ50hczaxVrrGkxJBhBRwVWbfLl/MW5BhiDnqzaJcBp67zi8mTIWSATLNUWtbiIYiFvzWrhoBJk6oB8R4hlAziJi9eDBiCCmAGTkfTcMxb4H2VowGEgPIqoq"
                + "Azuz8Zh+s/TpzmO+UNW3gIvqQqjK2NRH398gVVjmjyZvQVEle7cgTXzHVESQjKyag2WsSCUipd0vLSJYMkQ1sxQeEYtK1ObV2zANpBTFR/UDZbTgGKZ6tebD"
                + "dkCfUWcsrcnAqp3hXZABuQHuBCYq5pY606B/nQwRQgyPqx/hBRknYxXxIr25Xf04+c3t6sfJ/5EfuJ8XnRzD75cAAAAASUVORK5CYIJQSwMEFAAAAAgApgkF"
                + "XcZiHxxVAgAAUAIAABgAAAB3b2xmL3dvbGZfc25vd3lfdGFtZS5wbmcBUAKv/YlQTkcNChoKAAAADUlIRFIAAABAAAAAIAgDAAAAlUOOtgAAAC1QTFRFAAAA"
                + "///////69fXr5Ovk0NnatrvCpqu0n56tlJikgoGSOTw/GB8mEhQWFRMTLOg0XQAAAAF0Uk5TAEDm2GYAAAHRSURBVHja3dLBittAEEXRe6slJxDy/58aYqnr"
                + "hYxtPEYaL7LMaShebx4UlAAjGlONbjyt1hzTlooJG0cDoFRSCdg8KS0EIx2aowIQSRJM+GySScfJbJETCwAaShDhKQQSQm7hxLK2AhZtQS/GjTshAkpETlSS"
                + "sOMeMzvphgdBUEEw5wXq/kN+ThXR8CCUSqS05IRLKJSERpNq95UkWB0kGFSSmiNxh6cFwQI7AoLSAXUiSG57ShjYvFgEK0A1ACJoKMBHZxSCMYTPBPgGDRs8"
                + "rDEZYSqATo1zVBtmHw6J8CqqFUhIklKNojo4FOTQYCmFJIFCS4ZjwPC4wmXdAhv/YhkoBckoYOMCXLlb52COd9VlVXn9mABc9p2s3PVtvLEsa/OhtglQUpOH"
                + "iIY35K21V6ZXvrbAd5Ir/A2VX7yw4L0CiMAjvLKRd1zs6gr7xUjk90qHkiBpLLpYJlfOVEIqkYROEmgQbllotCCcKiKEQCedNBAIoPdkqsO5QokEDRgJEBLS"
                + "uX+U4lxpiAqUhUIQFEqQEKHzZUE5tCjLcgAqoARQSVOGU7U4argIw3IwUASCAqLDmOLUQvF4CAKIYgRBCD0Mp+RgJUYIcovC2LPzn/oDUgwK7RMIrNgAAAAA"
                + "SUVORK5CYIJQSwMEFAAAAAgApgkFXZ4UXnSbAQAAlgEAAB0AAAB3b2xmL3dvbGZfc25vd3lfdGFtZV9iYWJ5LnBuZwGWAWn+iVBORw0KGgoAAAANSUhEUgAA"
                + "ACAAAAAgCAMAAABEpIrGAAAAIVBMVEUAAAC2u8LQ2drk6+T19ev///oSFBaCgZKmq7SUmKSfnq3qDhZoAAAAAXRSTlMAQObYZgAAASNJREFUeNrVkgtygzAM"
                + "RLW/YOv+B+5gE2jSE/QNHobV4o+8VWUTVcEBhJTNUwNrsz+WYTC2I10/bXQRzgOhElEXdUKA5wjGAdNJuJVrju7ZPSfCYzJKYnX3PNVaAGs/GnNATixt7QIJ"
                + "yCov5Ni6tE3b/RhIWby0jWSvYXk/sSSP4VxdSFZhscyJHcmuk12zKYm0V1lL07MESUrab++qpboxSHpTBQJA/cYAcRtI/jWQsBJLIF/8nsMgEDuJsfg2hNwn"
                + "tGrTh3yfwprkvFoEYqjq6PuYciZJzn1TA4T6YjUqiV7AS7vHAODRozF6vJcIuxnbbwMHQK19UrLQQEPSbQCYHdx3QD+TLNIWWe/CY9zs26VO7xf1wZPqJ8kf"
                + "PKnuO8n/kR8sTQkQDdgUEwAAAABJRU5ErkJgglBLAwQUAAAACACmCQVdPBnh1y8CAAAqAgAAGAAAAHdvbGYvd29sZl9ibGFja190YW1lLnBuZwEqAtX9iVBO"
                + "Rw0KGgoAAAANSUhEUgAAAEAAAAAgBAMAAABQs2O3AAAAIVBMVEUAAAD///9FQEQ5NjwwLzkqKTAkISYcFxkRERMQDxIAAAAfMBCEAAAAAXRSTlMAQObYZgAA"
                + "AbdJREFUeNq9j8GO00AMhiOxLS/AiROy0xXiVNme5VplxuVaOnb2ipZNc0WCpuJxONKnJBvCblLBHvkkyzOaT/Y/RVEQSWAtBurj8T5ns2IKl9EgFAPhc5M5"
                + "J54JhBCxHM93gagKNBMSiMk4AfYCUAlMnrNmCuJRhxS4LwGrcipU8pFfRSQcBM4lP9Q0or5ufhhXv5dED/GhJkIMfvAsFmRhhBkYCNXCKm5GIWl76iy56gtA"
                + "BRYyAl6VsB4Fr7tD23jPVQyOKUXnFEuhN08pgg99obHZS0q12F4kPAk0Cle1fdtj5A/axBvd7h4FWI1C23QZiNu629427adH4W0vPAPDO8Dgu4UPM/e4uhAi"
                + "96jv7q7jEAjwQvh+Pp9/Hn339b0UPVhT8Sz5VBcXnPqIL7sv4635h3D686lDeyjmaAhpaSobp9KTV+h4zVNBxMIiy/06kxhrxFDOc3LKsjRu1hnYxBkCNjCb"
                + "YImXOeVNBIwsBEJHnGVIfYa8TbsK0diJSjrOVpirLuwmrKOgR6W+ddVUaHqWOcjaAlpyyiptnAqHnmXWtDEVV499u03F33BVT27msrXiv/ILfTB9MGAXgeUA"
                + "AAAASUVORK5CYIJQSwMEFAAAAAgApgkFXUBiuhhiAQAAXQEAAB0AAAB3b2xmL3dvbGZfYmxhY2tfdGFtZV9iYWJ5LnBuZwFdAaL+iVBORw0KGgoAAAANSUhE"
                + "UgAAACAAAAAgBAMAAACBVGfHAAAAGFBMVEUAAABFQEQ5NjwwLzkqKTAkISYcFxkSFBZFWVI0AAAAAXRSTlMAQObYZgAAAPNJREFUeNq1kEFOw1AMRE3FBexS"
                + "sa3HsCeeskckOQAlF+nRuQF2+HADnhJl9GLrf40IVrGrL/kk2KToj30qnP2rYKGrz3rpVGLd1s1e8a4PFXoE5qabThpw8xL3y5twDjd2Kj5OKQDSopPIQfWr"
                + "vZ11JILIDKQx6SWgAbK0mxMlMoiZC9wiGPvKZZlZL5hJaQ6uAM4Hw1l+BKzFnf6JWtdIvdXIELB9C79CLdJeKj3nfkrf2ViPXKNFnlKvGvQ4eqRI6vH2OAUB"
                + "mGb0ipsbWrhNEJkTBVtM7rXS1Y6+E8kW2y6LnhPhQHZG66PvYrS+9/2ffAOKlDSfagntDQAAAABJRU5ErkJgglBLAwQUAAAACACmCQVdiMuca48CAACKAgAA"
                + "GAAAAHdvbGYvd29sZl9hc2hlbl90YW1lLnBuZwGKAnX9iVBORw0KGgoAAAANSUhEUgAAAEAAAAAgCAMAAACVQ462AAAANlBMVEUAAAD////y9+3m7ebW3+C7"
                + "wMiko7Kckp+Ui5OJhI6Jfo5/fItva3tiWm45PD8YHyYSFBYVExMwiczjAAAAAXRSTlMAQObYZgAAAgJJREFUeNrd0rtyXEcMRdG90c2h7FHJ//+f5kvTjePg"
                + "Bp7SXDJQqJUgQOEEAAT4FqMf1ejif1ftanftsUdXv/FoALS6b5WAfd+UXdChAs3iUQFcCuopwYR7iyx2SCdFODEBtKOCyJ30e1hWADqcmddtsYGaFp2n6nrh"
                + "kF3B1qymlBOzQ9fHZH0zS5IIHBaQZEElhDPDcn38+Mk//zLYe3evbg4FoohSEB45RsJBt0m1+0ondDpIHIUWnbFmxzfuTDYqkDQgKDugc40beMnsJC2BbuDe"
                + "FJSgACCChgEoINRWCO3DpecCBlS4ARyqR++ZXgo/a4jVtTwmHh7pcTtdltxCQrJvWFbLsHQ+BnSacE+tFSQJZJXKHA6G8sAfzjn5LbMIFBurgMUVeIHDdWHm"
                + "C58bhfqhokB/f71d+vnGYfRuWHxujr8bAOq1AbSshsMtg918Qb40e7LrxucmXGgWwIVLv8I9C+Qrxb0ufmEiX/Gveqs53tnf34NT3q7s3JQgyZODZZ4W75yp"
                + "NBkdCUkmgQ1AkgCwwQnhVBEhBJFQAGEEUDIIEBPOFUpLgGi29JEb0kdgG0FOlSusUlCqLQgyFMqBBADDqbq19geSS9VzaoPKQAkDlYhyrlSKAhkjNJQUPAd9"
                + "hsLSiJwqREQAEY8qIkcFAnJKHlzpnUAQdBRbRvqNP9R/fbsnjXN/c3UAAAAASUVORK5CYIJQSwMEFAAAAAgApgkFXbwweFi1AQAAsAEAAB0AAAB3b2xmL3dv"
                + "bGZfYXNoZW5fdGFtZV9iYWJ5LnBuZwGwAU/+iVBORw0KGgoAAAANSUhEUgAAACAAAAAgBAMAAACBVGfHAAAAJ1BMVEUAAAD////y9+3m7ebW3+C7wMickp+U"
                + "i5OJhI5/fItva3tiWm4SFBZtxNwJAAAAAXRSTlMAQObYZgAAATdJREFUeNq1kLFOwzAQQI8uiAnZMCGGxlEl2KhPEcxAPoA2LWVFqo06tqrPrAzEMDGAaNlY"
                + "KHxG/4xzY/EHPCXK6UWyzg9AlWBX7lUfg6qAiR/7babZWfzFBEQ0H64vCsSALN6qsrLPdC72q/KmZKFkJs2P6YpcZTJjsbN8gbDwV7KIE/N58ARE9CCP4gTQ"
                + "Et1dYGRbpClQIK1zqm2og2NBxhMiUnDWDYhFPR/RBV7S/NrPccQi9IplH/nthJ4uILLtzFSpdkuqNjSCbBRb4k84OxO5FmvJphF0mwkVScLYmZYnPN3rzWL+"
                + "a8Jb8QPveRT1ZDxcGR+cv3OPNUA93lsfdkeBiKxxPi7GGWQn8JHO2gHAQisGoxi6cQ8gpk29T2mGTfXUm2+jmuqpN5Oqp95Mqr7p/Z/8AlY/YodVkOCqAAAA"
                + "AElFTkSuQmCCUEsDBBQAAAAIAKYJBV3b0SHbzQIAAMgCAAAYAAAAd29sZi93b2xmX3J1c3R5X3RhbWUucG5nAcgCN/2JUE5HDQoaCgAAAA1JSERSAAAAQAAA"
                + "ACAIAwAAAJVDjrYAAABLUExURQAAAP//////+vby6uvj19/UyODHrtypgMioksWRatKHT8N4QrdwQKhiSpZXQodTModSN4FNNnpLPHVMLmtCNGE6Kzk8P08z"
                + "KBIUFu+VSmoAAAABdFJOUwBA5thmAAACK0lEQVR42t3S0W4bRxSD4Z/cWSmwHQNpBfT9n69qDVQqIntneJLIQSLHayHIZb6L4d3gEKAA/ohjf3SQDny3k8c0"
                + "VMQxsOe1BvBovOSpgsyFOBEVzsIaA2wnmOYqVMWlTgYJIYHw1gV2jy0Q4kLGGJKmjJ4vyYq2iyEOvDfwouuIKQ2IzrnGJPQH/NCdnqSHbwICJeicrJimZh7+"
                + "Qvf/3Ihl9GTJE8+2SBhE7z144TXdSsA7TkCVqxwdd5ClqkaCPUmaDcS9Ee+50FT0Md2wjKmVEEgkMJvOAeo2jSSYGDovNWkZE4FpMANCYAcDFmAAGwLGCZfa"
                + "AXg3nU6wLCe+MfGSXoKTPGMgBmj99ZCK+oxLwgpxoRAZgZGx2usP0kNxSRammKyJwshisoUsLgng5u74CINf0W4pMFuEgQPvz+9Xu27S9rytaanB3zBpBuD+"
                + "yF1u/+dZMlC4os134cyPHTi3HuKrXgWdK8RV9xlM/o+3NfjAogPAB1rtealS5hoDqHhW4kclrtKd4rg4/vlUiC37HVkiZWF2lWfTnXnwL2vaxjHER0FhAukS"
                + "FCqQejM2hFUmgSygrSdvAEJVfV94IKqwrrHQW6tHoJlug4mqhASSzbmBWeVQ9F4FgJqB0ASlQqgRABxWeVRRA1E4hIAdSSoVUreJkVnXeqkUBqpQADitQ1FI"
                + "bjF2PMwqdzq9OgDG+Dk3GxCbjTFAgX96yjvopNJrtnCDGBV7flOfABh4O/6Zf3AiAAAAAElFTkSuQmCCUEsDBBQAAAAIAKYJBV3GkZCI6wEAAOYBAAAdAAAA"
                + "d29sZi93b2xmX3J1c3R5X3RhbWVfYmFieS5wbmcB5gEZ/olQTkcNChoKAAAADUlIRFIAAAAgAAAAIAgDAAAARKSKxgAAADxQTFRFAAAAlldCt3BAw3hCqGJK"
                + "yKiS39TI9vLq0odP///64Meu3KmAEhQW6+PXgU02TzMoYTorh1I3eks8a0I0+2QnKgAAAAF0Uk5TAEDm2GYAAAFYSURBVHja1ZIJcsMgDEXRF5udtLa+7n/X"
                + "goidpjfoG5axeEYjRikl1SwpGQ/Sct4fmmdMclqsjxDcTHXfgeunwB2B2XnQMh47MgYzHsIpkvOYRj/IrPuj54icrztKqWPUYnacZuj7rigRKTUFeRCpTqdr"
                + "HylwxQLZNoGmxAA6b7hiwfdX/VZcwiwTecXuKsg5oVAF6TS6OwFaCKSJTCEgXcSM7KUoQ3AKIOQsPmdSehe6olbFElwV+TwzSlm7qju0NizhymPGGqSkXWP/"
                + "BUnjLfTeW2t/BJvCtrVatfdn7zr4FEhrbQultbGUUn4LZpGijfO0cELvh6IfZsd6orWmRH+VGaEDNBy02zDnGPS4ykzwNHtC4jiwJXMKoqq9r6nyEua5OaeQ"
                + "AS21DWoBIAw8rogUV4N+drKQIi6XIPktLlQEENWoQvBCopM/eHf1u5M/eXf13cn/kR/vmxfcBMsYTAAAAABJRU5ErkJgglBLAwQUAAAACACmCQVdjF/QYgAD"
                + "AAD7AgAAGAAAAHdvbGYvd29sZl93b29kc190YW1lLnBuZwH7AgT9iVBORw0KGgoAAAANSUhEUgAAAEAAAAAgCAMAAACVQ462AAAAVFBMVEUAAAD////05tLd"
                + "0LrMvaW5rJeom4i8i1+UiXitglapflake0+XdU2Yck2Nb0uGZER7X0N2WTtsUTxmUjJYRy9MPixJPSpJOyo5PD8+MSI1Kx4SFBao8NVNAAAAAXRSTlMAQObY"
                + "ZgAAAlVJREFUeNrd0stuG0cQRuHzV/WQEhHHUCyASN7/3RI5Vm6jjEl2V1UWBAjCHHGRpb/uTe/6oEoAz6WSzx7gM1zsTeFhofDwUn3mVgNYpqa+9FMi40pg"
                + "YWQCFMEaA9g1aI9VqIprg+pEUVUpivd+4IySC4S4UqN3k7cCqGJN248GoYKPPhrhwAtniznpJ5qOJzbtvYRgeUWvswcRNYILO98x/1tGLDMr3JzD2y+mj3/K"
                + "OZ2O0U9x4myLGQ4jIkZGFre0ezwBP/AGbL564MGypzIOgyxE4e3BTVT6aJX2mSuNJIaJns0TPMCJAv8gxl+gT6iyAlFQQXKt+bHLskgbfXJwHIzEAQQkLmSQ"
                + "lG4mLYA9HOBvLvalA8XXRFD2iHgoDVla+ni92YPBN0q9gp4FKvIw4X0q4cis3W7iYJBcM8zBRFVh4IYxuRyX3SbsfvzHYeb/aDuC8Ah858DMJ+BSuR+o2gvv"
                + "a4wsfgNVA+D5D37i+QtnMRITd7TtUwCALwMgpPCAswWnd+4Qd32gMzHfTeCJwQzwxMP4Ha7ZMelb7jCujcY3siq5R88svmVh+fkt8K3zsidiCVGI8p07Q7Xp"
                + "fGFNcwhnQAIxZUD0DlSB4DjhOFCsspjHWCISAweA3kGAhM6vsCzWtWVUHYMCC6YMBwBlUSUDQCUQq9qoIkqAOYYDLQOJwhB4A0DvJVRJApEbs00QoO3kmEQZ"
                + "Pm1FCXPWNaGyssJy4szxiZiRdo4D8hJilSHOB3AcBwiCR/RAEAAkOKvaCc5+5eKQ4aekDrY5uj0AFN+v/wBbG0NyeB6OcQAAAABJRU5ErkJgglBLAwQUAAAA"
                + "CACmCQVdVwGjS9gBAADTAQAAHQAAAHdvbGYvd29sZl93b29kc190YW1lX2JhYnkucG5nAdMBLP6JUE5HDQoaCgAAAA1JSERSAAAAIAAAACAIAwAAAESkisYA"
                + "AAAzUExURQAAAMy9paibiN3Quj4xIpSJeDUrHod6Z4JePI1vSxIUFryLX6l+VoZkRGZSMlhHL0k7KiFQCu0AAAABdFJOUwBA5thmAAABTklEQVR42tWSAZKD"
                + "IAxFSQIUS5Kf+592JV20zp5g30zL+H2ixl9KUT1GKY4OeG1MVFc2jrJZBymEO4iEY1+URBgv3GuHNxbhxswWwZxCHa/WXq/miA40EpG2klHbKwUiIRIh917d"
                + "WUSIKROSktSTvFUNBK3zvLOki/RAKUhi7Rc7SzpRR2xhvSbXnSURwPqZmqoBAUdErMxTANzNAFvkCndgMitSCJjOaTjM7Dh+D0KZmewjhCq3VhufnEtj1Qgj"
                + "Jv4I130clJQyxsj1CwCOSzjG8VdwBzinpHO+59STpwA4kYjQzbfguQOTEO+om16DQlT3uke0/kvpUEsho6pwrfDL8IAHEEuA27S3+9tmTjrxj4wUTHUKIFPV"
                + "EKYnOW6PfJEaTBvmCE1sbaH5FLugzyYbkN/vbvUtJvk9TPWr1XeTn+xW301+crf6avJ/5Ac1uxbw3c3aFwAAAABJRU5ErkJgglBLAwQUAAAACACmCQVdmWps"
                + "vcUCAADAAgAAGwAAAHdvbGYvd29sZl9jaGVzdG51dF90YW1lLnBuZwHAAj/9iVBORw0KGgoAAAANSUhEUgAAAEAAAAAgCAMAAACVQ462AAAAUVBMVEUAAACr"
                + "kYabgniIcWqAamR1YVxoVVE6LjFQQUNDNThcSkwzKCsfHBoBAgLvt7HElZIiGiACAQEDBAVGODv///+Xf3OskYL21b/hwK7QsJ7CpZTQ3sunAAAAAXRSTlMA"
                + "QObYZgAAAh1JREFUeNrd1MFu20YURuFzrkgrDroo3Fqk9f7PZkuqC6RogcYxOX9iCEIkmNEiy3wEB3eAwVnMYgQYYzTV0Ee+67RVs72tFTPzXgHg/tlUknCu"
                + "JS0kDQgtLOgADiE7xmDCuT9bUW1vEio/DgzsMiiInEm62YSwIe5YUttabU2J7fCs7WH7sOVECIyMtDCypJL7MK0/TPF+bklrcDKAYIYoZFgODPqlzZlfdUA0"
                + "nAiqCKWypDPxU0/7/LoJWjGhI8mAmbEFeFJJ1bxKnC8CyL6rgtV+AwhKC6gzguRYlUAalzqhugnomgAiaE4tEEQhREwuA4/ASqS9PnJiqg1gEJBp2BubAKuZ"
                + "c3VaL8S7kSlFQt4w3hkp1dX7QL0r3GUyM5IEZpxyx6osSnnn4+8fb29v+Snd+NcaZuRlLOCRW+B/OOpmzGq6FrBv0IBeANY9L374zFEbgANXdFMfAHDqASJ5"
                + "FY7G1qjNjp+2He/vtxuuKPh2ZAu8Des/uDQVXFec++0/uDTJxDU+HB88njZdMAfmbtNCSZA0rMNsupnGkkpIJfIvSWYCDYQkAY/bFYRFRYQQ2sFP+38ECATQ"
                + "0xQTlhVKJNDvual2QwpCQloIVIwgi+og7C2BNcmN8ISgUII8AWBYVD7v/n77KQAEVEAJoBJRlnWdvdpLq2gIgkBQwKhGDEuKHL+zy0MUERQBArKoe4Gj0wCC"
                + "AhEBgcTwq/oKcDkkHI+RSYoAAAAASUVORK5CYIJQSwMEFAAAAAgApgkFXcCzxzvQAQAAywEAACAAAAB3b2xmL3dvbGZfY2hlc3RudXRfdGFtZV9iYWJ5LnBu"
                + "ZwHLATT+iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAMAAABEpIrGAAAANlBMVEUAAACIcWqbgniAamRQQUNcSkxoVVF1YVxDNTg6LjEkISbvt7HElZISFBb2"
                + "1b/hwK7QsJ6skYL0iOmPAAAAAXRSTlMAQObYZgAAAUNJREFUeNrVkguOhDAMQ/Mt7Hzi5P6XXRoGELMn2KdWVY1rpMhEBJQQCQ9mqUqgpiZFH/rSBhUBEJnH"
                + "oyarcm6RZbBURrTSmybLGDy3sA7mQkTU4F2liZlvy01kLCIZEUhrxZyadYOIVBdlxfyeh9b8PJ8/ZkTcJALIQ2vG6zWED0NVIuvQGlXm3qy8L2FVnZrQRKQi"
                + "b6BEqk+aJDAvmFIVgAggW8vdMB21kRt99ov20AmziDAaInPboOY0sPBpcPe/BhHm7CmZ+9u/MzpAgIiANd8G6YREIGnHHonPoArIITISUar7oIge9vFqJWKk"
                + "agzE6fDVtmUrEXUD8u3+zkBmcePmbutqn0FB3cwVQCY35t4RMyETqrahmmeCzgjuXxwFvTdZzZhT16vVl7EBzzxmulp9NvnG1erlbPKdq9Vnk/8jv+ODFcG4"
                + "SBQbAAAAAElFTkSuQmCCUEsDBBQAAAAIAKYJBV2RAI1rxgIAAMECAAAaAAAAd29sZi93b2xmX3N0cmlwZWRfdGFtZS5wbmcBwQI+/YlQTkcNChoKAAAADUlI"
                + "RFIAAABAAAAAIAgDAAAAlUOOtgAAAEhQTFRFAAAA////8NSk97OY3MGRzLKCv6d52JZ+rphvmYZih3ZYhXRWdWZMaFpDXFA/UUc4Rz8xRDwvPDQqNS4lICIj"
                + "AwQFAQICAgEBnvzMRQAAAAF0Uk5TAEDm2GYAAAInSURBVHja3ZHhbtswDIRV7u5KSTFZyV33/m86x0mxpIiDrT/3UTYFA/osncoZGAyEAKrcMOY61jFTUIpi"
                + "OQLwRohmuBNknOA9ElCQQDmium+DMBjLDQE3CAGjQ7ByBOkOiuD9DtxkoLkZz/2xQLVJqA6hdRHUnxwcMqP5vvpIQAf1EvFCwgGzmyABwQh89oMAqZefc/x6"
                + "EQHa7TEICSLapdfyCALqY87RBVCEwNLmOvoerbxq632ss3X3SPcvHpKa68YUSWnPgPKe0eQUHWiR3UWz2rJWK3dIOq1zYz3pkyKKcJlAECYHRRnYsvFBFJk5"
                + "xrj9EBWSzEDQIO27GBmRWz0QxBcBPDKaYEaTQS0yHAIy66PbjIh7gUR4RFTKVCPCQUlAVDM8ELzvgu/BjIiP7Ulqo5Rx65LZYirPqPlJ3QXzx4+ZWa7ADIbn"
                + "go/3Cx8XwfL6utRWrhjksPJ9hFrl5Tm1StfJfCv3uP5N8Da/CtyrPxdQEEQWFylkltFhRomUaIY+ImMP9iEgKEJlCKBnlp7poIj95ZndOE6HUQKkAJbZmXWO"
                + "LILHAhGUsIRDnnPEoYAiCZQ5aubIUbKaGYgNwsxqpi3D80DQ1FjVuAlGzrOghcMgAhIMHg2+9sMj9KUvbasyzoIcoxAZBomgYJGg5zrzSDDzUuX8921kGQ0y"
                + "iKQEE9rINpeWR4IrV8F+CyFQoiRCkR1tLGT5WyReFlPXKVqexPK/8hthqB9Zy8a0agAAAABJRU5ErkJgglBLAwQUAAAACACmCQVdP2FI79kBAADUAQAAHwAA"
                + "AHdvbGYvd29sZl9zdHJpcGVkX3RhbWVfYmFieS5wbmcB1AEr/olQTkcNChoKAAAADUlIRFIAAAAgAAAAIAgDAAAARKSKxgAAADxQTFRFAAAAv6d5UUc4h3ZY"
                + "mYZiPDQqRDwvaFpD97OY2JZ+NS4ldWZMAQICEhQWhXRWrphvXFA/8NSk3MGRzLKCINr/GwAAAAF0Uk5TAEDm2GYAAAFGSURBVHja1ZJbjsQwCAQBB2efsem+"
                + "/13XOMNIMzfYkiMrXZ3wg4gAeohE6ydClYBmdqjc1Is1P5sBCLI+2vDBsC+3oYygVibJ0dqRT4yvC1BEhGaSjyTuto65xdmHcXnQd+Imm75Y1zDvcyA9K9v4"
                + "x4ebiQD9GyACYGWb8/PzzGnT5gpVCWplm2a4jABB7GMXrBErD0nmCBspkryHxZgIGiDJAEYKJakKIDJBlilJSuqC5H3jtiDlCRARuBGxTbmaExhVmDbXkaL+"
                + "ADAC5LI/qwDgtXCfCExL5lshDUgEKDfdvUvCcQFsEY2Ia9wlinjvXvuALaMh0rU5G827PSqpgr/H8cvUnBvrZo8hJIArwwtAFdKb9ywoubwv5kVWwS0re0Qt"
                + "6Osmn816O92lRBWroDRT9lNE+Ia8U1v93OR3aqufm/wf+QPoNR18xF4kPQAAAABJRU5ErkJgglBLAwQUAAAACACmCQVd2RZkwmkAAABuAAAAEgAAAGNhdC9j"
                + "YXRfY29sbGFyLnBuZ+sM8HPn5ZLiYmBg4PX0cAkC0g5ArMABJBjavylGACmmkiC/YAaGsslnLYA8dU8Xx5CKW8kS1xLEBXgij7+/sTmZXaiaX+BtmgTr4gSR"
                + "nqZAA64XjAyTWrkXLPIIOAgyyNPVz2WdU0ITAFBLAwQUAAAACACmCQVd9/OGYmQAAABqAAAAFwAAAGNhdC9jYXRfY29sbGFyX2JhYnkucG5n6wzwc+flkuJi"
                + "YGDg9fRwCQLSCiDMASQYwgRVNYAUU0mQXzADQ9nksxZAnrKni2NIxa1kCVZn/je3NqeLq/767qDJJfLmJiNL9beeY0cN2Bmsg7jXXhT88QZkiKern8s6p4Qm"
                + "AFBLAwQUAAAACACmCQVdNtwOVI0AAACQAAAAFAAAAHdvbGYvd29sZl9jb2xsYXIucG5n6wzwc+flkuJiYGDg9fRwCQLSDkCswMECJDmmbOMHUuGeLo4hFbfe"
                + "Xl4oyqDIwxK4axk318KWKRt4A87N6Ty111g96Ya8aZdpz/4Wi0qnnrxFIdsXXCllNlu6S9erdLZO2b2kMh4LmaYT7Kcb3igIPPrqefYMCNjZOq+OW7lH67Av"
                + "0AoGT1c/l3VOCU0AUEsDBBQAAAAIAKYJBV34bRKgbAAAAHIAAAAZAAAAd29sZi93b2xmX2NvbGxhcl9iYWJ5LnBuZ+sM8HPn5ZLiYmBg4PX0cAkC0gogzAEk"
                + "GMIEVTWAFFNJkF8wA0PZ5LMWQJ62p4tjSMWtZImghJNhChFO1p+3KxmeDN7AMrWTM6306rWys00TeBYniPDkMTA0JvLtjfzM/wZkmKern8s6p4QmAFBLAQIU"
                + "ABQAAAAIAKYJBV0359T0FwIAABICAAARAAAAAAAAAAAAAAAAAAAAAABjYXQvY2F0X3RhYmJ5LnBuZ1BLAQIUABQAAAAIAKYJBV3+Pk40SgEAAEUBAAAWAAAA"
                + "AAAAAAAAAAAAAEYCAABjYXQvY2F0X3RhYmJ5X2JhYnkucG5nUEsBAhQAFAAAAAgApgkFXR6wMYg7AQAANgEAABEAAAAAAAAAAAAAAAAAxAMAAGNhdC9jYXRf"
                + "YmxhY2sucG5nUEsBAhQAFAAAAAgApgkFXe9WUe40AQAALwEAABYAAAAAAAAAAAAAAAAALgUAAGNhdC9jYXRfYmxhY2tfYmFieS5wbmdQSwECFAAUAAAACACm"
                + "CQVdPnmngTgCAAAzAgAADwAAAAAAAAAAAAAAAACWBgAAY2F0L2NhdF9yZWQucG5nUEsBAhQAFAAAAAgApgkFXZPHwalUAQAATwEAABQAAAAAAAAAAAAAAAAA"
                + "+wgAAGNhdC9jYXRfcmVkX2JhYnkucG5nUEsBAhQAFAAAAAgApgkFXcSUx0e9AQAAuAEAABMAAAAAAAAAAAAAAAAAgQoAAGNhdC9jYXRfc2lhbWVzZS5wbmdQ"
                + "SwECFAAUAAAACACmCQVd4GByWEEBAAA8AQAAGAAAAAAAAAAAAAAAAABvDAAAY2F0L2NhdF9zaWFtZXNlX2JhYnkucG5nUEsBAhQAFAAAAAgApgkFXSwwc76W"
                + "AQAAkQEAAB0AAAAAAAAAAAAAAAAA5g0AAGNhdC9jYXRfYnJpdGlzaF9zaG9ydGhhaXIucG5nUEsBAhQAFAAAAAgApgkFXY4iB8UUAQAAEgEAACIAAAAAAAAA"
                + "AAAAAAAAtw8AAGNhdC9jYXRfYnJpdGlzaF9zaG9ydGhhaXJfYmFieS5wbmdQSwECFAAUAAAACACmCQVdqlJLZRICAAANAgAAEgAAAAAAAAAAAAAAAAALEQAA"
                + "Y2F0L2NhdF9jYWxpY28ucG5nUEsBAhQAFAAAAAgApgkFXVaogGlcAQAAVwEAABcAAAAAAAAAAAAAAAAATRMAAGNhdC9jYXRfY2FsaWNvX2JhYnkucG5nUEsB"
                + "AhQAFAAAAAgApgkFXQiLXUl/AQAAegEAABMAAAAAAAAAAAAAAAAA3hQAAGNhdC9jYXRfcGVyc2lhbi5wbmdQSwECFAAUAAAACACmCQVdeOWqbBUBAAATAQAA"
                + "GAAAAAAAAAAAAAAAAACOFgAAY2F0L2NhdF9wZXJzaWFuX2JhYnkucG5nUEsBAhQAFAAAAAgApgkFXco0ZKSiAQAAnQEAABMAAAAAAAAAAAAAAAAA2RcAAGNh"
                + "dC9jYXRfcmFnZG9sbC5wbmdQSwECFAAUAAAACACmCQVdU0ZTNyIBAAAfAQAAGAAAAAAAAAAAAAAAAACsGQAAY2F0L2NhdF9yYWdkb2xsX2JhYnkucG5nUEsB"
                + "AhQAFAAAAAgApgkFXdjCF32aAQAAlQEAABEAAAAAAAAAAAAAAAAABBsAAGNhdC9jYXRfd2hpdGUucG5nUEsBAhQAFAAAAAgApgkFXaimMqQeAQAAGwEAABYA"
                + "AAAAAAAAAAAAAAAAzRwAAGNhdC9jYXRfd2hpdGVfYmFieS5wbmdQSwECFAAUAAAACACmCQVdqDjhaikCAAAkAgAAEgAAAAAAAAAAAAAAAAAfHgAAY2F0L2Nh"
                + "dF9qZWxsaWUucG5nUEsBAhQAFAAAAAgApgkFXYZg7jJuAQAAaQEAABcAAAAAAAAAAAAAAAAAeCAAAGNhdC9jYXRfamVsbGllX2JhYnkucG5nUEsBAhQAFAAA"
                + "AAgApgkFXd/SeFiXAQAAkgEAABUAAAAAAAAAAAAAAAAAGyIAAGNhdC9jYXRfYWxsX2JsYWNrLnBuZ1BLAQIUABQAAAAIAKYJBV3Ir35iGwEAABoBAAAaAAAA"
                + "AAAAAAAAAAAAAOUjAABjYXQvY2F0X2FsbF9ibGFja19iYWJ5LnBuZ1BLAQIUABQAAAAIAKYJBV0XUduPjwIAAIoCAAASAAAAAAAAAAAAAAAAADglAAB3b2xm"
                + "L3dvbGZfdGFtZS5wbmdQSwECFAAUAAAACACmCQVdzoHfq54BAACZAQAAFwAAAAAAAAAAAAAAAAD3JwAAd29sZi93b2xmX3RhbWVfYmFieS5wbmdQSwECFAAU"
                + "AAAACACmCQVdYgTzIj0DAAA4AwAAGgAAAAAAAAAAAAAAAADKKQAAd29sZi93b2xmX3Nwb3R0ZWRfdGFtZS5wbmdQSwECFAAUAAAACACmCQVd5cxyuu0BAADo"
                + "AQAAHwAAAAAAAAAAAAAAAAA/LQAAd29sZi93b2xmX3Nwb3R0ZWRfdGFtZV9iYWJ5LnBuZ1BLAQIUABQAAAAIAKYJBV3GYh8cVQIAAFACAAAYAAAAAAAAAAAA"
                + "AAAAAGkvAAB3b2xmL3dvbGZfc25vd3lfdGFtZS5wbmdQSwECFAAUAAAACACmCQVdnhRedJsBAACWAQAAHQAAAAAAAAAAAAAAAAD0MQAAd29sZi93b2xmX3Nu"
                + "b3d5X3RhbWVfYmFieS5wbmdQSwECFAAUAAAACACmCQVdPBnh1y8CAAAqAgAAGAAAAAAAAAAAAAAAAADKMwAAd29sZi93b2xmX2JsYWNrX3RhbWUucG5nUEsB"
                + "AhQAFAAAAAgApgkFXUBiuhhiAQAAXQEAAB0AAAAAAAAAAAAAAAAALzYAAHdvbGYvd29sZl9ibGFja190YW1lX2JhYnkucG5nUEsBAhQAFAAAAAgApgkFXYjL"
                + "nGuPAgAAigIAABgAAAAAAAAAAAAAAAAAzDcAAHdvbGYvd29sZl9hc2hlbl90YW1lLnBuZ1BLAQIUABQAAAAIAKYJBV28MHhYtQEAALABAAAdAAAAAAAAAAAA"
                + "AAAAAJE6AAB3b2xmL3dvbGZfYXNoZW5fdGFtZV9iYWJ5LnBuZ1BLAQIUABQAAAAIAKYJBV3b0SHbzQIAAMgCAAAYAAAAAAAAAAAAAAAAAIE8AAB3b2xmL3dv"
                + "bGZfcnVzdHlfdGFtZS5wbmdQSwECFAAUAAAACACmCQVdxpGQiOsBAADmAQAAHQAAAAAAAAAAAAAAAACEPwAAd29sZi93b2xmX3J1c3R5X3RhbWVfYmFieS5w"
                + "bmdQSwECFAAUAAAACACmCQVdjF/QYgADAAD7AgAAGAAAAAAAAAAAAAAAAACqQQAAd29sZi93b2xmX3dvb2RzX3RhbWUucG5nUEsBAhQAFAAAAAgApgkFXVcB"
                + "o0vYAQAA0wEAAB0AAAAAAAAAAAAAAAAA4EQAAHdvbGYvd29sZl93b29kc190YW1lX2JhYnkucG5nUEsBAhQAFAAAAAgApgkFXZlqbL3FAgAAwAIAABsAAAAA"
                + "AAAAAAAAAAAA80YAAHdvbGYvd29sZl9jaGVzdG51dF90YW1lLnBuZ1BLAQIUABQAAAAIAKYJBV3As8c70AEAAMsBAAAgAAAAAAAAAAAAAAAAAPFJAAB3b2xm"
                + "L3dvbGZfY2hlc3RudXRfdGFtZV9iYWJ5LnBuZ1BLAQIUABQAAAAIAKYJBV2RAI1rxgIAAMECAAAaAAAAAAAAAAAAAAAAAP9LAAB3b2xmL3dvbGZfc3RyaXBl"
                + "ZF90YW1lLnBuZ1BLAQIUABQAAAAIAKYJBV0/YUjv2QEAANQBAAAfAAAAAAAAAAAAAAAAAP1OAAB3b2xmL3dvbGZfc3RyaXBlZF90YW1lX2JhYnkucG5nUEsB"
                + "AhQAFAAAAAgApgkFXdkWZMJpAAAAbgAAABIAAAAAAAAAAAAAAAAAE1EAAGNhdC9jYXRfY29sbGFyLnBuZ1BLAQIUABQAAAAIAKYJBV3384ZiZAAAAGoAAAAX"
                + "AAAAAAAAAAAAAAAAAKxRAABjYXQvY2F0X2NvbGxhcl9iYWJ5LnBuZ1BLAQIUABQAAAAIAKYJBV023A5UjQAAAJAAAAAUAAAAAAAAAAAAAAAAAEVSAAB3b2xm"
                + "L3dvbGZfY29sbGFyLnBuZ1BLAQIUABQAAAAIAKYJBV34bRKgbAAAAHIAAAAZAAAAAAAAAAAAAAAAAARTAAB3b2xmL3dvbGZfY29sbGFyX2JhYnkucG5nUEsF"
                + "BgAAAAAsACwA9gsAAKdTAAAAAA==";

    private DDPolymerCollarPack() {
    }

    static void register() {
        var event = PolymerResourcePackUtils.RESOURCE_PACK_AFTER_INITIAL_CREATION_EVENT;
        event.addPhaseOrdering(Event.DEFAULT_PHASE, PACK_PHASE);
        // Default-phase contributors can enqueue pre-finish work that writes
        // these same vanilla masks. Queue our work from an after-default phase
        // so it is appended after theirs and the transparent donor masks and
        // matching composites are always the final resource definitions.
        event.register(PACK_PHASE, builder -> builder.addPreFinishTask(DDPolymerCollarPack::addCollarTextures));
    }

    static boolean supportsVariant(String type, Identifier variant) {
        if (!"minecraft".equals(variant.getNamespace())) {
            return false;
        }
        return switch (type) {
            case "cat" -> Arrays.asList(CAT_VARIANTS).contains(variant.getPath());
            case "wolf" -> WOLF_VARIANTS.containsKey(variant.getPath());
            default -> false;
        };
    }

    private static void addCollarTextures(ResourcePackBuilder builder) {
        Map<String, byte[]> sources = unpackSources();
        byte[] catAdultMask = required(sources, "cat/cat_collar.png");
        byte[] catBabyMask = required(sources, "cat/cat_collar_baby.png");
        byte[] wolfAdultMask = required(sources, "wolf/wolf_collar.png");
        byte[] wolfBabyMask = required(sources, "wolf/wolf_collar_baby.png");

        addTransparentMask(builder, "cat/cat_collar.png", catAdultMask);
        addTransparentMask(builder, "cat/cat_collar_baby.png", catBabyMask);
        addTransparentMask(builder, "wolf/wolf_collar.png", wolfAdultMask);
        addTransparentMask(builder, "wolf/wolf_collar_baby.png", wolfBabyMask);

        for (String variant : CAT_VARIANTS) {
            byte[] adult = required(sources, "cat/cat_" + variant + ".png");
            byte[] baby = required(sources, "cat/cat_" + variant + "_baby.png");
            for (DyeColor color : collarColors()) {
                String root = "assets/dye_depot/textures/entity/cat/collar/minecraft/"
                        + variant + "/" + color.getName();
                builder.addData(root + ".png", composite(adult, catAdultMask, color));
                builder.addData(root + "_baby.png", composite(baby, catBabyMask, color));
            }
        }

        WOLF_VARIANTS.forEach((variant, source) -> {
            byte[] adult = required(sources, "wolf/" + source + "_tame.png");
            byte[] baby = required(sources, "wolf/" + source + "_tame_baby.png");
            for (DyeColor color : collarColors()) {
                String root = "assets/dye_depot/textures/entity/wolf/collar/minecraft/"
                        + variant + "/" + color.getName();
                builder.addData(root + "/tame.png", composite(adult, wolfAdultMask, color));
                builder.addData(root + "/tame_baby.png", composite(baby, wolfBabyMask, color));
            }
        });
    }

    private static DyeColor[] collarColors() {
        DyeColor[] colors = new DyeColor[32];
        for (int id = 0; id < colors.length; id++) {
            colors[id] = DyeColor.byId(id);
            if (colors[id].getId() != id) {
                throw new IllegalStateException("Missing Dye Depot collar color id " + id);
            }
        }
        return colors;
    }

    private static Map<String, byte[]> unpackSources() {
        Map<String, byte[]> sources = new HashMap<>();
        byte[] archive = Base64.getDecoder().decode(SOURCE_TEXTURES_ZIP);
        try (ZipInputStream zip = new ZipInputStream(new ByteArrayInputStream(archive))) {
            ZipEntry entry;
            while ((entry = zip.getNextEntry()) != null) {
                if (!entry.isDirectory()) {
                    sources.put(entry.getName(), zip.readAllBytes());
                }
            }
        } catch (IOException exception) {
            throw new IllegalStateException("Could not unpack embedded collar textures", exception);
        }
        if (sources.size() != 44) {
            throw new IllegalStateException("Expected 44 embedded collar textures, found " + sources.size());
        }
        return sources;
    }

    private static byte[] required(Map<String, byte[]> sources, String path) {
        byte[] texture = sources.get(path);
        if (texture == null) {
            throw new IllegalStateException("Missing embedded collar texture " + path);
        }
        return texture;
    }

    private static void addTransparentMask(ResourcePackBuilder builder, String path, byte[] source) {
        BufferedImage mask = readPng(source, path);
        builder.addData(
                "assets/minecraft/textures/entity/" + path,
                encodePng(new BufferedImage(mask.getWidth(), mask.getHeight(), BufferedImage.TYPE_INT_ARGB), path)
        );
    }

    private static byte[] composite(byte[] baseBytes, byte[] maskBytes, DyeColor color) {
        BufferedImage base = readPng(baseBytes, "collar base");
        BufferedImage mask = readPng(maskBytes, "collar mask");
        if (base.getWidth() != mask.getWidth() || base.getHeight() != mask.getHeight()) {
            throw new IllegalStateException("Collar base and mask dimensions differ for " + color.getName());
        }

        BufferedImage output = new BufferedImage(base.getWidth(), base.getHeight(), BufferedImage.TYPE_INT_ARGB);
        int tint = color.getTextureDiffuseColor();
        for (int y = 0; y < base.getHeight(); y++) {
            for (int x = 0; x < base.getWidth(); x++) {
                int background = rawArgb(base, x, y);
                int maskPixel = rawArgb(mask, x, y);
                int alpha = ARGB.alpha(maskPixel);
                if (alpha == 0) {
                    output.setRGB(x, y, background);
                    continue;
                }
                int foreground = ARGB.color(
                        alpha,
                        tint(ARGB.red(maskPixel), ARGB.red(tint)),
                        tint(ARGB.green(maskPixel), ARGB.green(tint)),
                        tint(ARGB.blue(maskPixel), ARGB.blue(tint))
                );
                output.setRGB(x, y, sourceOver(background, foreground));
            }
        }
        return encodePng(output, "composite " + color.getName() + " collar");
    }

    private static int rawArgb(BufferedImage image, int x, int y) {
        // ImageIO maps grayscale PNG samples through a linear-gray ColorSpace
        // when getRGB is called (for example, native sample 186 becomes 222).
        // Minecraft uploads the PNG samples directly, so preserve the raster
        // value to keep both the body and native collar-mask shading exact.
        if (image.getColorModel().getNumColorComponents() == 1) {
            int gray = image.getRaster().getSample(x, y, 0);
            int alpha = image.getRaster().getNumBands() > 1
                    ? image.getRaster().getSample(x, y, image.getRaster().getNumBands() - 1)
                    : ARGB.alpha(image.getRGB(x, y));
            return ARGB.color(alpha, gray, gray, gray);
        }
        return image.getRGB(x, y);
    }

    private static int tint(int texture, int color) {
        return Math.round(texture * color / 255.0f);
    }

    private static int sourceOver(int background, int foreground) {
        int foregroundAlpha = ARGB.alpha(foreground);
        if (foregroundAlpha == 255) {
            return foreground;
        }
        int backgroundAlpha = ARGB.alpha(background);
        int inverse = 255 - foregroundAlpha;
        int outputAlpha = foregroundAlpha + Math.round(backgroundAlpha * inverse / 255.0f);
        if (outputAlpha == 0) {
            return 0;
        }
        return ARGB.color(
                outputAlpha,
                blendChannel(ARGB.red(background), backgroundAlpha, ARGB.red(foreground), foregroundAlpha, inverse, outputAlpha),
                blendChannel(ARGB.green(background), backgroundAlpha, ARGB.green(foreground), foregroundAlpha, inverse, outputAlpha),
                blendChannel(ARGB.blue(background), backgroundAlpha, ARGB.blue(foreground), foregroundAlpha, inverse, outputAlpha)
        );
    }

    private static int blendChannel(
            int background,
            int backgroundAlpha,
            int foreground,
            int foregroundAlpha,
            int inverse,
            int outputAlpha
    ) {
        float premultiplied = foreground * foregroundAlpha
                + background * backgroundAlpha * inverse / 255.0f;
        return Math.round(premultiplied / outputAlpha);
    }

    private static BufferedImage readPng(byte[] data, String description) {
        try {
            BufferedImage image = ImageIO.read(new ByteArrayInputStream(data));
            if (image == null) {
                throw new IllegalStateException("Embedded " + description + " is not a PNG");
            }
            return image;
        } catch (IOException exception) {
            throw new IllegalStateException("Could not decode " + description, exception);
        }
    }

    private static byte[] encodePng(BufferedImage image, String description) {
        try {
            ByteArrayOutputStream output = new ByteArrayOutputStream();
            ImageIO.write(image, "png", output);
            return output.toByteArray();
        } catch (IOException exception) {
            throw new IllegalStateException("Could not encode " + description, exception);
        }
    }
}
