package com.ninni.dye_depot.data.server;

import com.google.gson.JsonArray;
import com.google.gson.JsonObject;
import com.ninni.dye_depot.data.DDJsonProvider;
import com.ninni.dye_depot.data.ModCompat;
import net.fabricmc.fabric.api.datagen.v1.FabricPackOutput;
import net.minecraft.world.item.DyeColor;

/**
 * Optional block loot generated by identifier. All 48 tables require the
 * target mod and its corresponding Supplementaries feature flag.
 */
public final class DDCompatLoot extends DDJsonProvider {

    public DDCompatLoot(FabricPackOutput output) {
        super(output);
    }

    @Override
    protected void generate(Output output) {
        ModCompat.colors().forEach(color -> {
            generateCandleHolder(output, color, ModCompat.SUPPLEMENTARIES, "candle_holder");
            generateCandleHolder(output, color, ModCompat.SUPPLEMENTARIES_SQUARED, "gold_candle_holder");
            generateFlag(output, color);
        });
    }

    private void generateCandleHolder(Output output, DyeColor color, String namespace, String type) {
        String name = type + "_" + color.getSerializedName();
        String id = namespace + ":" + name;
        JsonObject loot = lootTable(id, candleEntry(id), false);
        ModCompat.addSupplementariesConditions(loot, namespace, "candle_holder");
        output.accept(data(namespace, "loot_table/blocks", name), loot);
    }

    private void generateFlag(Output output, DyeColor color) {
        String name = "flag_" + color.getSerializedName();
        String id = ModCompat.SUPPLEMENTARIES + ":" + name;

        JsonObject entry = new JsonObject();
        entry.addProperty("type", "minecraft:item");
        entry.addProperty("name", id);
        JsonObject copy = new JsonObject();
        copy.addProperty("function", "minecraft:copy_components");
        copy.addProperty("source", "block_entity");
        JsonArray include = new JsonArray();
        include.add("minecraft:custom_name");
        include.add("minecraft:item_name");
        include.add("minecraft:tooltip_display");
        include.add("minecraft:rarity");
        include.add("minecraft:banner_patterns");
        copy.add("include", include);
        JsonArray functions = new JsonArray();
        functions.add(copy);
        entry.add("functions", functions);

        JsonObject loot = lootTable(id, entry, true);
        ModCompat.addSupplementariesConditions(loot, ModCompat.SUPPLEMENTARIES, "flag");
        output.accept(data(ModCompat.SUPPLEMENTARIES, "loot_table/blocks", name), loot);
    }

    private static JsonObject candleEntry(String blockId) {
        JsonObject entry = new JsonObject();
        entry.addProperty("type", "minecraft:item");
        entry.addProperty("name", blockId);
        JsonArray functions = new JsonArray();
        for (int count = 2; count <= 4; count++) {
            JsonObject condition = new JsonObject();
            condition.addProperty("condition", "minecraft:block_state_property");
            condition.addProperty("block", blockId);
            JsonObject properties = new JsonObject();
            properties.addProperty("candles", Integer.toString(count));
            condition.add("properties", properties);
            JsonArray conditions = new JsonArray();
            conditions.add(condition);

            JsonObject setCount = new JsonObject();
            setCount.addProperty("function", "minecraft:set_count");
            setCount.addProperty("count", (float) count);
            setCount.add("conditions", conditions);
            functions.add(setCount);
        }
        JsonObject explosionDecay = new JsonObject();
        explosionDecay.addProperty("function", "minecraft:explosion_decay");
        functions.add(explosionDecay);
        entry.add("functions", functions);
        return entry;
    }

    private static JsonObject lootTable(String id, JsonObject entry, boolean poolExplosionDecay) {
        JsonArray entries = new JsonArray();
        entries.add(entry);
        JsonObject pool = new JsonObject();
        pool.addProperty("rolls", 1.0F);
        pool.add("entries", entries);
        if (poolExplosionDecay) {
            JsonObject explosionDecay = new JsonObject();
            explosionDecay.addProperty("function", "minecraft:explosion_decay");
            JsonArray functions = new JsonArray();
            functions.add(explosionDecay);
            pool.add("functions", functions);
        }

        JsonArray pools = new JsonArray();
        pools.add(pool);
        JsonObject loot = new JsonObject();
        loot.addProperty("type", "minecraft:block");
        loot.add("pools", pools);
        loot.addProperty("random_sequence", id.substring(0, id.indexOf(':') + 1) + "blocks/" + id.substring(id.indexOf(':') + 1));
        return loot;
    }

    @Override
    public String getName() {
        return "Dye Depot optional compatibility loot";
    }
}
